# 🔹 Он собирает README.md из трёх частей
# 🔹 Поддерживает ручной запуск и автоматический запуск при изменении файлов в `.github/README_PARTS/`
# 🔹 Публикация в ветку main ## если нужно запушить в другую ветку то вконце скрипта меняем `main` в `HEAD:main` на вашу ветку
# 🔹 Работает на стандартных GitHub runners (ubuntu-latest)

name: Build README from parts

on:
  workflow_dispatch: # ручной запуск
  push:
    paths:
    - ".github/README_PARTS/*" # срабатывает при изменении исходных файлов

jobs:
  build-readme:
    runs-on: ubuntu-latest
    name: 📄 Генерация README.md из частей
    steps:
    - name: 🔄 Вывод информации о запуске
      run: |
        echo "🎉 Запущено событием ${{ github.event_name }}"
        echo "🐧 Операционная система: ${{ runner.os }}"

    - name: 📥 Клонирование репозитория
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # полная история коммитов
        clean: true # очистка рабочей директории перед сборкой

    - name: 🛠 Настройка Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: 📂 Объединение частей README
      run: |
        HEADER=".github/README_PARTS/1.HEADER.md"
        DESCRIPTION=".github/README_PARTS/2.DESCRIPTION.md"
        DONATION=".github/README_PARTS/3.DONATION.md"
        NAV=".github/README_PARTS/4.NAV.md"
        MAIN=".github/README_PARTS/5.MAIN.md"
        FOOTER=".github/README_PARTS/6.FOOTER.md"
        OUTPUT="README.md"

        # Проверка существования файлов
        if [[ ! -f "$HEADER" || ! -f "$DESCRIPTION" || ! -f "$FOOTER" ]]; then
          echo "❌ Ошибка: отсутствует один из входных файлов!"
          exit 1
        fi

        # Объединяем все части с двумя пустыми строками между блоками
        cat "$HEADER" > "$OUTPUT"
        echo -e "\n\n" >> "$OUTPUT"
        cat "$DESCRIPTION" >> "$OUTPUT"
        echo -e "\n\n" >> "$OUTPUT"
        cat "$DONATION" >> "$OUTPUT"
        echo -e "\n\n" >> "$OUTPUT"
        cat "$NAV" >> "$OUTPUT"
        echo -e "\n\n" >> "$OUTPUT"
        cat "$MAIN" >> "$OUTPUT"
        echo -e "\n\n" >> "$OUTPUT"
        cat "$FOOTER" >> "$OUTPUT"
        echo -e "\n\n" >> "$OUTPUT"


        echo "✅ README.md успешно сгенерирован."

    - name: 💾 Commit и Push README
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add README.md
        git commit -m "Auto-generate README from parts" || echo "ℹ️ Нет изменений для фиксации"
        git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git" HEAD:main
